variable "COMPONENT" {}
variable "ENV" {}
variable "ENGINE_VERSION" {}
variable "SKIP_FINAL_SNAPSHOT" {}
variable "SUBNET_IDS" {}
variable "VPC_ID" {}
variable "ENGINE" {}
variable "INSTANCE_CLASS" {}
variable "CIDR_BLOCK" {}
variable "AZ" {}
